EventManager/EventManager/ViewModels/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EventManager.ViewModels
{
    public class EventViewModel
    {
        [Key]
        public int Id { get; set; }

        [Display(Name="Event Name")]
        [Required(ErrorMessage = "Event Name field is reqiured")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Field reqiures only letters and minimum 8 characters")]
        public string Name { get; set; }

        [Display(Name = "Event Location")]
        [Required(ErrorMessage = "Event Location field is reqiured")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "Field reqiures only letters and minimum 10 characters")]
        public string Location { get; set; }

        [Display(Name = "Start Date")]
        [Required(ErrorMessage = "Start Date field is reqiured")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [Required(ErrorMessage = "End Date field is reqiured")]
        public DateTime EndDate { get; set; }  
        
    }
}

EventManager/EventManager/Controllers/EventsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EventManager.Repositories;
using EventManager.DAL;
using AutoMapper;
using EventManager.ViewModels;

namespace EventManager.Controllers
{
    public class EventsController : Controller
    {
        private EventsEntities _db = new EventsEntities();
        private IRepository<Event> _repository = null;

        public EventsController()
        {
            this._repository = new Repository<Event>();
        }

        // GET: Events
        public ActionResult List()
        {
            var events = _repository.SelectAll().ToList();
            var eventViewModel = Mapper.Map<List<EventViewModel>>(events);
            return View(eventViewModel);
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            var events = _repository.SelectByID(id.Value);
            var eventViewModel = Mapper.Map<EventViewModel>(events);
            return View(eventViewModel);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            var eventViewModel = new EventViewModel();
            return View(eventViewModel);
        }

        // POST: Events/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventViewModel eventViewModel)
        {
            var events = new Event();
            var newEvent = Mapper.Map(eventViewModel, events);
            _repository.Insert(newEvent);
            _repository.Save();
            return RedirectToAction("List");
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            var selectedEvent = _repository.SelectByID(id.Value);
            var eventViewModel = new EventViewModel();
            var editedEvent = Mapper.Map(selectedEvent, eventViewModel);
            return View(editedEvent);
        }

        // POST: Events/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, EventViewModel eventViewModel)
        {
            var selectedEvent = _repository.SelectByID(id.Value);
            var editedEvent = Mapper.Map(eventViewModel, selectedEvent);
            _repository.Update(editedEvent);
            _repository.Save();
            return RedirectToAction("List");
        }

        // GET: Events/Delete/5
        public ActionResult Delete()
        {
            var model = new EventViewModel();
            return View(model);
        }

        // POST: Events/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(EventViewModel eventViewModel, int? id)
        {
            var selectedEvent = _repository.SelectByID(id.Value);
            var deletedEvent = Mapper.Map(eventViewModel, selectedEvent);
            _repository.Delete(deletedEvent);
            _repository.Save();
            return RedirectToAction("List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventManager/EventManager/Controllers/HomeController.cs
using System.Web.Mvc;

namespace EventManager.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

EventManager/EventManager/Views/Events/Create.cshtml
@model EventManager.ViewModels.EventViewModel

@{
    ViewBag.Title = "Create New Event";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create New Event</h2>
<div class="form-horizontal">
    @Html.AntiForgeryToken()

    @using (Html.BeginForm("Create", "Events", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name" } })
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @placeholder = "Location" } })
                @Html.ValidationMessageFor(model => model.Location, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "20-02-2018 00:00:00" } })
                @Html.ValidationMessageFor(model => model.StartDate, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "21-02-2018 00:00:00" } })
                @Html.ValidationMessageFor(model => model.EndDate, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventManager/EventManager/Views/Events/Delete.cshtml
@model EventManager.ViewModels.EventViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3 style="color:brown; text-align:center">Are you sure you want to delete this event?</h3>
<div class="row">
    @using (Html.BeginForm("Delete", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => Model.Id)
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="col-md-2 col-md-offset-5">
            <div class="row justify-content-center">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a class="btn btn-warning" href="../List" role="button">Go back</a>
            </div>
        </div>
    }
</div>

EventManager/EventManager/Views/Events/Details.cshtml
﻿@model EventManager.ViewModels.EventViewModel

@{
    ViewBag.Title = "Event Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Event Details</h2>
<div>
    <table class="table table-striped text-center">
        <thead>
            <tr>
                <td>
                    @Html.LabelFor(x => Model.Id)
                </td>
                <td>
                    @Html.LabelFor(x => Model.Name)
                </td>
                <td>
                    @Html.LabelFor(x => Model.Location)
                </td>
                <td>
                    @Html.LabelFor(x => Model.StartDate)
                </td>
                <td>
                    @Html.LabelFor(x => Model.EndDate)
                </td>
            </tr>
        </thead>
        <tr>
            <td>
                @Html.DisplayFor(x => Model.Id)
            </td>
            <td>
                @Html.DisplayFor(x => Model.Name)
            </td>
            <td>
                @Html.DisplayFor(x => Model.Location)
            </td>
            <td>
                @Html.DisplayFor(x => Model.StartDate)
            </td>
            <td>
                @Html.DisplayFor(x => Model.EndDate)
            </td>
        </tr>
    </table>
</div>
<div>
    <a class="btn btn-info" href="../List" role="button">Go back</a>
</div>

EventManager/EventManager/Views/Events/Edit.cshtml
@model EventManager.ViewModels.EventViewModel

@{
    ViewBag.Title = "Edit Event";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit Event</h2>
<div class="form-horizontal">
    @Html.AntiForgeryToken()

    @using (Html.BeginForm("Edit", "Events", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-warning">Edit</button>
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventManager/EventManager/Views/Events/List.cshtml
@model List<EventManager.ViewModels.EventViewModel>
@{
    ViewBag.Title = "List of events";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Current Events</h2>
<div>
    <table class="table table-striped text-center">
        @foreach (var item in Model)
        {
            <thead>
                <tr>
                    <td style="font-weight:bold">
                        №
                    </td>
                    <td>
                        @Html.LabelFor(x => item.Name)
                    </td>
                    <td>
                        @Html.LabelFor(x => item.Location)
                    </td>
                    <td>
                        @Html.LabelFor(x => item.StartDate)
                    </td>
                    <td>
                        @Html.LabelFor(x => item.EndDate)
                    </td>
                    <td style="font-weight:bold">
                        Actions
                    </td>
                </tr>
            </thead>
            break;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(x => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(x => item.EndDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>
<div>
    <a class="btn btn-primary" href="../Events/Create" role="button">Create new event</a>
</div>

EventManager/EventManager/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<p>
    <strong>Assignment:</strong><br />
    Application for managing events.<br />
    The following information is stored for each event: name, location, start date and time, end date and time (all are required).<br />
    The application should allow you to read all events, create a new event, update an existing event and delete it.
</p>

EventManager/EventManager/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacts";
}
<address>
    <abbr title="Phone">Phone number:</abbr>
    +359 883 404 783
</address>
<address>
    <strong>Email:</strong>   <a href="mailto:borislava.yordanova8@gmail.com">borislava.yordanova8@gmail.com</a><br />
</address>

EventManager/EventManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<img src="http://prikachi.com/images/595/9270595l.png" height="195" width="800">
<div class="jumbotron">
    <p class="lead">
        The information you will find for each event is: the name, the location, the start date and end date time.<br />
        The application should allow you to read all events, create a new event, to update an existing event and to delete it.
    </p>
    <p><a href="https://edu.protal.biz/mod/assign/view.php?id=123" class="btn btn-primary btn-lg">See more &raquo;</a></p>
</div>

EventManager/EventManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Event Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Event Manager
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Current events", "List", "Events") </li>
                            <li>@Html.ActionLink("Create new event", "Create", "Events")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Event Manager</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>